# Generated by Django 5.2.4 on 2025-07-22 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_exam', '0003_user_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
